# https://docs.vllm.ai/en/v0.9.2/examples/online_serving/prometheus_grafana.html#example-materials

global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: vllm
    static_configs:
      - targets:
          - "host.docker.internal:8000"
